config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'team-single' => 'contacts#team-single', as: 'team-single'
  root to: "home#index"

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :restaurants do
    resources :restaurant_photos
  end
  resources :contacts
  resources :reviews

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  def destroy
    super if should_destroy?
  end

  def should_destroy?
    id != 1
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :restaurants

  validates_presence_of :title
  validates_uniqueness_of :title

  scope :published, -> { where(published: true) }
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :message
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  ratyrate_rateable 'service'

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :category
  belongs_to :user, optional: true
  has_many :restaurant_photos
  has_many :reviews

  scope :published, -> { where(published: true) }

  geocoded_by :address do |obj,results|
    obj.send :ensure_geocoding, results.first
  end

  validates :street_address, :province, :city, :zip, :country, presence: true
  after_validation :assign_address
  after_validation :geocode, if: ->  (obj) { obj.address.present? and obj.address_changed? }

  def ensure_geocoding(geo)
    if geo
      self.latitude = geo.latitude
      self.longitude = geo.longitude
      self.address = geo.formatted_address
    else
      errors.add(:address, '^Please provide a valid address')
    end
  end

  def coordinates_blank?
    (latitude.blank? || longitude.blank? || !Rails.env.test?)
  end

  def assign_address
    self.address = [street_address, city, province, country, zip].compact.join(', ')
  end

  def primary_photo_url
    restaurant_photos.where(primary: true).try(:first).try(:photo).try(:url)
  end

  def self.search(params)
    restaurants = Restaurant.published
    restaurants = restaurants.where("LOWER(name) LIKE (?)", "%#{params[:name].downcase}%") if params[:name].present?
    restaurants = restaurants.where("LOWER(address) LIKE (?)", "%#{params[:keyword].downcase}%") if params[:keyword].present?
    restaurants = restaurants.joins(:category).where("LOWER(categories.title) = ?", 'params[:category].downcase') if params[:category].present? && !params[:category].eql?('category')
    restaurants
  end

  def claimed?
    user_id.present?
  end
end

app/models/restaurant_photo.rb
class RestaurantPhoto < ApplicationRecord
  belongs_to :restaurant

  has_attached_file :photo, styles: { thumb: "100x100>", big: "500x500>" }, default_url: "//s3.amazonaws.com/pickeat/eateries/default_photos/default-thumbnail.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  scope :not_primary, -> { where(primary: false) }
end

app/models/review.rb
class Review < ApplicationRecord
  validates :user_id, uniqueness: { scope: [:restaurant_id]}
  validates_presence_of :comment_title
  validates_presence_of :comment
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         def confirmation_required?
           true
         end
  
  has_many :reviews
  has_many :restaurants
         
  ratyrate_rater  
  
  def has_eatery?
    true if restaurants.count > 0
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index 
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(permitted_params)
    if @contact.save
      redirect_to contacts_path, notice: "Thank you for your feedback."
    else
      flash[:error] = 'Please provide your message.'
      redirect_to contacts_path
    end
  end

  private

  def permitted_params
    params.require(:contact).permit(
      :name,
      :email,
      :phone,
      :subject, 
      :message
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    published_restaurants = Restaurant.published
    @restaurants = published_restaurants.last(8)
    @random_eateries = published_restaurants.order("RANDOM()").last(8)
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token  

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

    def new
      @review.Review.new
    end

    def create
      @review = current_user.reviews.build(review_params)
      if @review.save
        redirect_to @review.restaurant
      else
        flash[:danger] = "You already added a review to this eatery!"
        redirect_to @review.restaurant
      end
    end

    private

      def review_params
        params.require(:review).permit(
          :comment_title, 
          :comment,
          :rating,
          :restaurant_id)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
  def lat_lng
    @lat_lng = cookies[:lat_lng].split("|") if cookies[:lat_lng]
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def category_options
    Category.published.map(&:title).push("category").reverse
  end

  def static_map_for(location, options = {})
    params = {
      :q => location.address,
      :key => ENV["GOOGLE_API_KEY"]
      }.merge(options)
    query_string = params.map{|k,v| "#{k}=#{v}"}.join("&")
    return "https://www.google.com/maps/embed/v1/place?#{query_string}"
  end

  def user_rated?(user, restaurant)
    rate = Rate.find_by(rater: user, rateable: restaurant)
    true if rate.present?
  end

  def rating_per_user(restaurant, user)
    rate = Rate.where(rateable: restaurant, rater_id: user.id).first
    rate.present? ? rate.stars : 0
  end

  def overall_rating_per_restaurant(restaurant, star)
    Rate.where(rateable: restaurant, stars: star).size
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/extras/coming-soon.html.erb
<!doctype html>
<html lang="en-US">

    <head>

        <title>PICK EAT - The Real Estate</title>

        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />

        <script src="js/pace.js"></script>

        <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="css/flexslider.css" type="text/css">
        <link rel="stylesheet" href="css/jquery.selectBox.css" type="text/css">
        <link rel="stylesheet" href="css/jquery-ui.css" type="text/css">
        <link rel="stylesheet" href="css/font-awesome.min.css" type="text/css">
        <link rel="stylesheet" href="css/green.css" type="text/css">
        <link rel="stylesheet" href="css/style.css" type="text/css">
        <link rel="stylesheet" href="css/responsive.css" type="text/css">
        <link rel="stylesheet" href="css/pace-minimal.css">

        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,700,500' rel='stylesheet' type='text/css'>

        <link rel="shortcut icon" href="favicon.ico">

        <!--[if lt IE 9]>
            <script src="js/html5shiv.js"></script>
        <![endif]-->

    </head>

    <body class="offline coming-soon">

        <!-- HEADER -->
        <header class="clearfix">

            <div class="left-side clearfix">

                <div class="logo">
                    <a href="#"><img src="<%=asset_url('logo.png')%>" alt="PICK EAT">PICK EAT</a>
                </div>

            </div>

            <div class="right-side">

                <div class="adress">
                    <a href="#">121 King Street, Melbourne Victoria 3000 Australia</a>
                </div>

                <div class="phone">
                    <a href="tel:+61383766284">+ 613 8376 6284</a>
                </div>

            </div>

        </header>
        <!-- HEADER -->

        <!-- ERROR -->
        <div class="page-wrap error-page">

            <div class="container-fluid">
                <div class="row-fluid">
                    <div class="col-md-12">
                        <h4>Coming Soon</h4>
                        <div class="progress-bar">
                            <div style="width: 70%;"></div>
                        </div>
                        <div class="cycle-slideshow" data-cycle-slides="> div" data-cycle-timeout="5000" data-cycle-prev="#comingsoon-slider-control .prev" data-cycle-next="#comingsoon-slider-control .next">
                            <div><p><span>110 835</span>Seconds Left</p></div>
                            <div><p><span>7 835</span>Minutes Left</p></div>
                            <div><p><span>130</span>Hours Left</p></div>
                        </div>
                        <div id="comingsoon-slider-control" class="slider-control">
                            <a href="#" class="prev"><i class="fa fa-angle-left"></i>In Seconds</a>
                            <a href="#" class="next">In Hours<i class="fa fa-angle-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- ERROR -->

        <!-- FOOTER -->
        <footer>
            <div class="container-fluid">
                <div class="row-fluid">
                    <div class="col-md-12 copy-right">
                        <p>&copy; 2018 PICK EAT - Where finding food matters</p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- FOOTER -->

        <script src="js/jquery-1.11.3.min.js"></script>
        <script src="js/jquery-ui.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/masonry.pkgd.min.js"></script>
        <script src="js/jquery.flexslider-min.js"></script>
        <script src="js/jquery.selectBox.min.js"></script>
        <script src="js/icheck.js"></script>
        <script src="js/counter.animation.js"></script>
        <script src="js/jquery.appear.js"></script>
        <script src="js/custom.js"></script>
        <script src="js/jquery.cycle2.js"></script>

    </body>
</html>

app/views/extras/error.html.erb
<!doctype html>
<html lang="en-US">

    <head>

        <title>PICK EAT - The Real Estate</title>

        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />

        <script src="js/pace.js"></script>

        <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="css/flexslider.css" type="text/css">
        <link rel="stylesheet" href="css/jquery.selectBox.css" type="text/css">
        <link rel="stylesheet" href="css/jquery-ui.css" type="text/css">
        <link rel="stylesheet" href="css/font-awesome.min.css" type="text/css">
        <link rel="stylesheet" href="css/green.css" type="text/css">
        <link rel="stylesheet" href="css/style.css" type="text/css">
        <link rel="stylesheet" href="css/responsive.css" type="text/css">
        <link rel="stylesheet" href="css/pace-minimal.css">

        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,700,500' rel='stylesheet' type='text/css'>

        <link rel="shortcut icon" href="favicon.ico">

        <!--[if lt IE 9]>
            <script src="js/html5shiv.js"></script>
        <![endif]-->

    </head>

    <body>

        <!-- TOP -->
        <div class="top-bar">

            <p class="text">
                <a><i class="fa fa-map-marker"></i> 121 King Street, Melbourne Victoria 3000 Australia</a>
                <a href="tel:+61383766284"><i class="fa fa-phone"></i> + 613 8376 6284</a>
            </p>

            <p class="social">
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-vimeo"></i></a>
                <a href="#"><i class="fa fa-instagram"></i></a>
                <a href="#"><i class="fa fa-skype"></i></a>
            </p>

        </div>
        <!-- TOP -->

        <!-- HEADER -->
        <header class="clearfix">

            <div class="logo">
                <a href="<%=root_path%>"><img src="<%=asset_url('logo.png')%>" alt="PICK EAT">PICK EAT</a>
            </div>

            <nav class="navbar collapse" id="mobile-menu">
                <ul class="nav navbar-nav">
                    <li><a href="<%=root_path%>">Home</a></li>
                    <li><a href="about.html">About Us</a></li>
                    <li><a href="#">Eatery</a></li>
                    <li><a href="#">Team</a></li>
                    <li><a href="contact.html">Contact Us</a></li>
                </ul>
            </nav>

            <div class="user">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="images/avatar1.png" alt="User Photo">
                    <span class="drop-arow"></span>
                </a>
                <ul class="dropdown-menu user-drop">
                    <li><a href="#"><i class="fa fa-user"></i>My Profile</a></li>
                    <li><a href="#"><i class="fa fa-list"></i>My Properties</a></li>
                    <li><a href="#"><i class="fa fa-sign-out"></i>Logout</a></li>
                </ul>
            </div>

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mobile-menu" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

        </header>
        <!-- HEADER -->

        <!-- ERROR -->
        <div class="page-wrap error-page">

            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h4>404</h4>
                        <h6>Error</h6>
                        <p>Page Not Found</p>
                        <a href="#" class="btn btn-danger">Back to Home</a>
                    </div>
                </div>
            </div>

        </div>
        <!-- ERROR -->

        <!-- FOOTER -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-5 copy-right">
                        <p><img src="<%=asset_url('footer-logo.png')%>" alt="Logo" class="img-responsive"> &copy; 2018 PICK EAT — Where finding food matters</p>
                    </div>
                    <div class="col-md-7">
                        <ul>
                            <li><a href="#">Home</a></li>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Eatery</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- FOOTER -->

        <script src="js/jquery-1.11.3.min.js"></script>
        <script src="js/jquery-ui.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/masonry.pkgd.min.js"></script>
        <script src="js/jquery.flexslider-min.js"></script>
        <script src="js/jquery.selectBox.min.js"></script>
        <script src="js/icheck.js"></script>
        <script src="js/counter.animation.js"></script>
        <script src="js/jquery.appear.js"></script>
        <script src="js/custom.js"></script>
        <script src="js/jquery.cycle2.js"></script>

    </body>
</html>

app/views/extras/offline.html.erb
<!doctype html>
<html lang="en-US">

    <head>

        <title>PICK EAT - The Real Estate</title>

        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />

        <script src="js/pace.js"></script>

        <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="css/flexslider.css" type="text/css">
        <link rel="stylesheet" href="css/jquery.selectBox.css" type="text/css">
        <link rel="stylesheet" href="css/jquery-ui.css" type="text/css">
        <link rel="stylesheet" href="css/font-awesome.min.css" type="text/css">
        <link rel="stylesheet" href="css/green.css" type="text/css">
        <link rel="stylesheet" href="css/style.css" type="text/css">
        <link rel="stylesheet" href="css/responsive.css" type="text/css">
        <link rel="stylesheet" href="css/pace-minimal.css">

        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,700,500' rel='stylesheet' type='text/css'>

        <link rel="shortcut icon" href="favicon.ico">

        <!--[if lt IE 9]>
            <script src="js/html5shiv.js"></script>
        <![endif]-->

    </head>

    <body class="offline">

        <!-- HEADER -->
        <header class="clearfix">

            <div class="left-side clearfix">

                <div class="logo">
                    <a href="#"><img src="<%=asset_url('logo.png')%>" alt="PICK EAT">PICK EAT</a>
                </div>

            </div>

            <div class="right-side">

                <div class="adress">
                    <a href="#">121 King Street, Melbourne Victoria 3000 Australia</a>
                </div>

                <div class="phone">
                    <a href="tel:+61383766284">+ 613 8376 6284</a>
                </div>

            </div>

        </header>
        <!-- HEADER -->

        <!-- ERROR -->
        <div class="page-wrap error-page">

            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Site Offline</h4>
                        <p>Please come back later.</p>
                    </div>
                </div>
            </div>

        </div>
        <!-- ERROR -->

        <!-- FOOTER -->
        <footer>
            <div class="container-fluid">
                <div class="row-fluid">
                    <div class="col-md-12 copy-right">
                        <p>&copy; 2018 PICK EAT - Where finding food matters</p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- FOOTER -->

        <script src="js/jquery-1.11.3.min.js"></script>
        <script src="js/jquery-ui.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/masonry.pkgd.min.js"></script>
        <script src="js/jquery.flexslider-min.js"></script>
        <script src="js/jquery.selectBox.min.js"></script>
        <script src="js/icheck.js"></script>
        <script src="js/counter.animation.js"></script>
        <script src="js/jquery.appear.js"></script>
        <script src="js/custom.js"></script>
        <script src="js/jquery.cycle2.js"></script>

    </body>
</html>

app/views/shared/_footer.html.erb
<!-- CALL2ACTION -->
<div class="full-width call-action">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <h4>Want to improve your eatery? contact us now!</h4>
      </div>
        <div class="col-md-3">
          <a href="<%=contacts_path%>" class="btn btn-danger">Create an Eatery</a>
        </div>
    </div>
  </div>
</div>
<!-- CALL2ACTION -->
<!-- FOOTER -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-5 copy-right">
        <p><img src="<%=asset_url('footer-logo.png')%>" alt="Logo"
          class="img-responsive"> &copy; 2018 PICK EAT — Where finding food matters</p>
      </div>
      <div class="col-md-7">
        <ul>
          <li><a href="<%= root_path %>">Home</a></li>
          <li><a href="<%= restaurants_path %>">Eatery</a></li>
          <li><a href="<%=contacts_path%>">About</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
<!-- FOOTER -->

app/views/shared/_header.html.erb
<!-- TOP -->
<div class="top-bar">
  <p class="text">
    <span><i class="fa fa-map-marker"></i> Naga City 4400 Camarines Sur Philippines </span>
  </p>
  <p class="social">
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-vimeo"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-skype"></i></a>
  </p>
</div>
<!-- TOP -->
<!-- HEADER -->
<header class="clearfix">
  <div class="logo">
    <a href="<%=root_path%>"><img src="<%=asset_url('logo.png')%>" alt="PICK EAT">PICK EAT</a>
  </div>
    <nav class="navbar collapse" id="mobile-menu">
      <ul class="nav navbar-nav">
        <li><a href="<%= root_path %>">Home</a></li>
        <li><a href="<%= restaurants_path %>">Eatery</a></li>
        <li><a href="<%= contacts_path %>">About</a></li>
      </ul>
    </nav>
    <% if user_signed_in? %>
    <div class="user">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <p><%= current_user.first_name %></p>
        <span class="drop-arow"></span><i class="fa fa-caret-down"
        style="font-size:25px;"></i>
      </a>
      <ul class="dropdown-menu user-drop">
        <li><%=link_to 'Edit Profile', edit_user_registration_path %></li>
        <% if current_user.has_eatery? %>
          <li style="padding: 12px 25px; font-weight: bold;">My Eateries</li>
          <% current_user.restaurants.each do |restaurant| %>
            <li><%=link_to "#{restaurant.name}", restaurant_path(restaurant) %></li>
          <% end %>
        <% end %>
        <div class="divider"></div>
        <li><%=link_to 'Logout', destroy_user_session_path, method: :delete,
        data: { confirm: 'Are you sure?' }%></li>
      </ul>
    </div>
    <% else %>
    <div class="user">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-user-circle" style="font-size:25px;"></i>
          <span class="drop-arow"></span>
      </a>
      <ul class="dropdown-menu user-drop">
        <li><%=link_to 'Log In', new_user_session_path %></li>
        <li><%=link_to 'Sign Up', new_user_registration_path%></li>
      </ul>
    </div>
    <% end %>
    <button type="button" class="navbar-toggle" data-toggle="collapse"
    data-target="#mobile-menu" aria-expanded="false">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
</header>
<!-- HEADER -->

app/views/shared/_roulette.html.erb
<h1 class="h1-main">Where to?</h1>
<div class="carousel container-fluid" data-gap="60" data-bfc>
  <figure>
    <% @random_eateries.each do |restaurant| %>
    <div class="container-fluid container-bg" id="square">
      <div class="row">
        <div class="col-sm-6 pull-left"><h4><%=restaurant.name%>
          <% if restaurant.claimed? %>
          <i class="fa fa-check-circle" style="color:#EA4E3C;font-size:20px;"></i></h4></a>
        </h4>
          <% else %>
          <h6 style="font-size:10px"><i class="fa fa-times-circle" style="color:#EA4E3C;font-size:20px;"></i> Unclaimed yet!</h6>
          <% end %>
        </div>
        <div class="col-sm-4 pull-right"><h6><strong>OPEN HOURS: <%=restaurant.open_hours %>
        <br>PHONE: <%=restaurant.phone%></strong></h6></div>
      </div>
    <div class="row">
        <div class="col-sm-12"><h5 class="font-add"><%=restaurant.address%></h5></div>
        <div class="row">
        <div class="col-sm-7 containerho">
          <img src="<%=restaurant.primary_photo_url%>" class="imageho img-responsive" alt="eateryimage">
            <div class="middleho">
              <a href="<%=restaurant_path(restaurant)%>" class="btn btn-danger">Pick Me</a>
            </div>
        </div>
        <div class="col-sm-5">
          <iframe
            frameborder="0" style="border:0"
            src="<%=static_map_for(restaurant)%>" class="img-responsive" allowfullscreen>
          </iframe>
            <br>
          <% if lat_lng.present? %>
            <span class="area">DISTANCE: <%=number_to_human(restaurant.distance_from(lat_lng, :km),
            units:
            :distance,
            precision: 4)%>
          </span>
          <% end %>
          <%=rating_for restaurant, 'service', disable_after_rate: true %>
            <br>
            <h5>Price Range:<h5> <h6><%=restaurant.price_range%></h6>
            <br><br>
            <h6><%=restaurant.reviews.size%> Reviews</h6>
          </div>
          </div>
        </div>
      </div>
      <% end %>
    </figure>
    <nav>
      <br><br><br><br><br>
      <button class=" nav btn btn-danger next">Spin</button>
    </nav>
</div>
<script>
/*carousel*/
var carousels;
window.addEventListener('load', () => {
        carousels = document.querySelectorAll('.carousel');

    for (var i = 0; i < carousels.length; i++) {
        carousel(carousels[i]);
    }
});

function carousel(root) {
    var
        figure = root.querySelector('figure'),
        nav = root.querySelector('nav'),
        images = figure.children,
        n = images.length,
        gap = root.dataset.gap || 0,
        bfc = 'bfc' in root.dataset,

        theta =  2 * Math.PI / n,
        currImage = 0
    ;

    setupCarousel(n, parseFloat(getComputedStyle(images[0]).width));
    window.addEventListener('resize', () => {
        setupCarousel(n, parseFloat(getComputedStyle(images[0]).width))
    });

    setupNavigation();

    function setupCarousel(n, s) {
        var
            apothem = s / (2 * Math.tan(Math.PI / n))
        ;

        figure.style.transformOrigin = `50% 50% ${- apothem}px`;

        for (var i = 0; i < n; i++)
            images[i].style.padding = `${gap}px`;
        for (i = 1; i < n; i++) {
            images[i].style.transformOrigin = `50% 50% ${- apothem}px`;
            images[i].style.transform = `rotateY(${i * theta}rad)`;
        }
        if (bfc)
            for (i = 0; i < n; i++)
                images[i].style.backfaceVisibility = 'hidden';

        rotateCarousel(currImage);
    }

    function setupNavigation() {
        nav.addEventListener('click', onClick, true);

        function onClick(e) {
            e.stopPropagation();

            var t = e.target;
            if (t.tagName.toUpperCase() != 'BUTTON')
                return;

            if (t.classList.contains('next')) {
                console.log(carousels.length);
                var randomnumber=Math.floor(Math.random()*16)
                currImage = currImage + randomnumber;
            }
            else {
                currImage--;
            }

            rotateCarousel(currImage);
        }

    }

    function rotateCarousel(imageIndex) {
        figure.style.transform = `rotateY(${imageIndex * -theta}rad)`;
    }

}
</script>