config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'team-single' => 'contacts#team-single', as: 'team-single'
  root to: "home#index"

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :restaurants do
    resources :restaurant_photos
  end
  resources :contacts
  resources :reviews

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  ratyrate_rateable 'service'

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :category
  belongs_to :user, optional: true
  has_many :restaurant_photos
  has_many :reviews

  scope :published, -> { where(published: true) }

  geocoded_by :address do |obj,results|
    obj.send :ensure_geocoding, results.first
  end

  validates :street_address, :province, :city, :zip, :country, presence: true
  after_validation :assign_address
  after_validation :geocode, if: ->  (obj) { obj.address.present? and obj.address_changed? }

  def ensure_geocoding(geo)
    if geo
      self.latitude = geo.latitude
      self.longitude = geo.longitude
      self.address = geo.formatted_address
    else
      errors.add(:address, '^Please provide a valid address')
    end
  end

  def coordinates_blank?
    (latitude.blank? || longitude.blank? || !Rails.env.test?)
  end

  def assign_address
    self.address = [street_address, city, province, country, zip].compact.join(', ')
  end

  def primary_photo_url
    restaurant_photos.where(primary: true).try(:first).try(:photo).try(:url)
  end

  def self.search(params)
    restaurants = Restaurant.published
    restaurants = restaurants.where("LOWER(name) LIKE (?)", "%#{params[:name].downcase}%") if params[:name].present?
    restaurants = restaurants.where("LOWER(address) LIKE (?)", "%#{params[:keyword].downcase}%") if params[:keyword].present?
    restaurants = restaurants.joins(:category).where("LOWER(categories.title) = ?", 'params[:category].downcase') if params[:category].present? && !params[:category].eql?('category')
    restaurants
  end

  def claimed?
    user_id.present?
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # before_action :authenticate_user!
  before_action :find_restaurant, only: [:show, :edit, :update]
  before_action :owner, only: :edit

  def index
    @restaurants = Restaurant.search(params).page(params[:page]).per(10)
  end

  def show
    @reviews = @restaurant.reviews
  end

  def edit
  end

  def update
    @restaurant.update_attributes(permitted_params)
    if @restaurant.valid?
      flash.now[:success] = "Eatery successfully updated"
      render action: :edit
    else
      flash.now[:error] = @restaurant.errors.full_messages.join(', ')
      render action: :edit
    end
  end

  def owner
    unless @restaurant.user_id == current_user.id
      flash[:notice] = 'Access denied as you are not owner of this Eatery'
      redirect_to restaurants_path
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.friendly.find(params[:id])
  end

  def permitted_params
    params.require(:restaurant).permit(
      :id,
      :name,
      :street_address,
      :city,
      :zip,
      :province,
      :country,
      :price_range,
      :phone,
      :open_hours
    )
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def category_options
    Category.published.map(&:title).push("category").reverse
  end

  def static_map_for(location, options = {})
    params = {
      :q => location.address,
      :key => ENV["GOOGLE_API_KEY"]
      }.merge(options)
    query_string = params.map{|k,v| "#{k}=#{v}"}.join("&")
    return "https://www.google.com/maps/embed/v1/place?#{query_string}"
  end

  def user_rated?(user, restaurant)
    rate = Rate.find_by(rater: user, rateable: restaurant)
    true if rate.present?
  end

  def rating_per_user(restaurant, user)
    rate = Rate.where(rateable: restaurant, rater_id: user.id).first
    rate.present? ? rate.stars : 0
  end

  def overall_rating_per_restaurant(restaurant, star)
    Rate.where(rateable: restaurant, stars: star).size
  end
end

app/views/restaurants/_reviews.html.erb
<style>
.rating-block{
	background-color:#FAFAFA;
	border:1px solid #EFEFEF;
	padding:15px 15px 20px 15px;
	border-radius:3px;
}
.bold{
	font-weight:700;
}
.padding-bottom-7{
	padding-bottom:7px;
}

.review-block{
	background-color:#FAFAFA;
	border:1px solid #EFEFEF;
	padding:10px;
	border-radius:3px;
	margin-bottom:15px;
}
.review-block-name{
	font-size:15px;
	margin:10px 0;
}
.review-block-date{
	font-size:13px;
}
.review-block-rate{
	font-size:13px;
	margin-bottom:15px;
}
.review-block-title{
	font-size:25px;
	font-weight:700;
	margin-bottom:10px;
}
.review-block-description{
	font-size:17px;
}
</style>
<div class="container">
	<div class="row">
		<div class="col-sm-9">
			<div class="rating-block">
				<h4>Average user rating</h4>
				<%=rating_for @restaurant, 'service', disable_after_rate: true,
				imdb_avg: true %>
			</div>
		</div>
		<% if @reviews.any? %>
			<div class="row">
				<div class="col-sm-12">
					<hr/>
					<div class="review-block">
						<% @reviews.each do |review| %>
						<div class="row">
							<div class="col-sm-3">
								<img src="http://dummyimage.com/60x60/666/ffffff&text=No+Image"
								class="img-rounded">
								<div class="review-block-name"><a href="#"><%= review.user.first_name%></a></div>
								<div class="review-block-date"><%= review.created_at %></div>
							</div>
							<div class="col-sm-9">
								<div class="review-block-rate">
									<% (0..rating_per_user(review.restaurant, review.user)).each do %>
										<%=image_tag 'star-on.png'%>
									<% end %>
								</div>
								<div class="review-block-title"><%= review.comment_title %></div>
								<div class="review-block-description"><%= review.comment %></div>
							</div>
						</div>
						<hr/>
						<% end %>
					</div>
				</div>
			</div>
		<% end %>
    </div> <!-- /container -->

app/views/restaurants/edit.html.erb
<div class="container">
  <div class="row col-md-4 col-md-offset-4">
    <h2>Edit your Eatery</h2>

    <%= form_for(@restaurant) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :street_address %>
        <%= f.text_field :street_address, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :province %>
        <%= f.text_field :province, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :country %>
        <br/>
        <%= f.select :country, options_for_select(ActionView::Helpers::FormOptionsHelper::COUNTRIES), selected: f.object.country %>
      </div>

      <div class="form-group">
        <%= f.label :phone %>
        <%= f.text_field :phone, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :open_hours %>
        <%= f.text_field :open_hours, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :price_range %>
        <%= f.text_field :price_range, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit "Submit", class: 'btn btn-danger' %>
        &nbsp;
        <%= link_to 'Edit Photos', restaurant_restaurant_photos_path(f.object), class: 'btn btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="full-width page-wrap properties-page">
  <!-- BREADCRUMBS-->
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumbs">
          <a href="<%= root_path %>">Home</a>
          <span class="sep">/</span>
          <span class="current">Eatery</span>
        </div>
        <h2 class="page-title">All Eateries</h2>
      </div>
    </div>
  </div>
  <!-- BREADCRUMBS -->
  <div class="container">
    <div class="row">
      <!-- SIDEBAR -->
      <aside class="col-md-4">
        <div class="property-search">
          <%= form_tag restaurants_path, method: 'get' do %>
            <label>Name (e.g. Kinalas)</label>
            <%=text_field_tag :name, params[:name], class: 'form-control' %>
            <label>Address (e.g. Magsaysay)</label>
            <%=text_field_tag :keyword, params[:keyword], class: 'form-control' %>
            <br/>
            <%=select_tag :category, options_for_select(category_options, params[:category]) %>
            <hr>
            <div class="buttons">
              <button class="btn btn-danger"><i class="fa fa-search"></i>Search</button>
              <%=link_to 'Clear', restaurants_path, class: 'btn btn-clear'%>
            </div>

          <% end %>
        </div>
      </aside>
      <!-- SIDEBAR -->
      <div class="col-md-8">
        <div class="row properties-grid">
          <% @restaurants.in_groups_of(2).each do |restaurants| %>
            <div class="row">
              <% restaurants.each do |restaurant| %>
                <% if restaurant.present? %>
                  <div class="col-md-6 col-sm-6">
                    <div class="item">
                      <div class="item-header clearfix">
                        <h3><a href="<%=restaurant_path(restaurant)%>"><%=restaurant.name%></a>
                        <% if restaurant.claimed? %>
                          <i class="fa fa-check-circle" style="color:#EA4E3C;font-size:20px;"></i>
                        <% else %>
                          <i class="fa fa-times-circle" style="color:#EA4E3C;font-size:20px;"></i>
                        <% end %>
                        </h3>
                        <div class="pull-right">
                          <%=rating_for restaurant, 'service', disable_after_rate: true %>
                        </div>
                      </div>
                      <figure>
                        <img src="<%=restaurant.primary_photo_url%>" alt=""
                        class="img-responsive">
                        <div class="overlay">
                          <a href="<%=restaurant_path(restaurant)%>" class="btn
                            btn-detail">Detail</a>
                        </div>
                      </figure>
                      <div class="item-detail">
                        <div class="left">
                          <span class="place"><i class="fa fa-map-marker"></i><%=restaurant.address%></span>
                        </div>
                        <div class="right">
                          <% if lat_lng.present? %>
                            <span class="area">DISTANCE: <%=number_to_human(restaurant.distance_from(lat_lng, :km),
                            units:
                            :distance,
                            precision: 4)%>
                          </span>
                          <% end %>
                          <br><br>
                          <span class="price">‎<%=restaurant.price_range%></span>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <!-- PAGINATION -->
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="pagination">
          <%= paginate @restaurants %>
        </div>
      </div>
    </div>
  </div>
  <!-- PAGINATION -->
</div>

app/views/restaurants/show.html.erb
<div class="page-wrap properties-page property-single">
  <!-- BREADCRUMBS-->
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumbs">
          <a href="<%= root_path %>">Home</a>
          <span class="sep">/</span>
          <span class="current"><%=@restaurant.name%></span>
        </div>
        <h2 class="page-title"><%=@restaurant.name%>
        <% if user_signed_in?%>
          <% if @restaurant.claimed? %>
            <i class="fa fa-check-circle" style="color:#EA4E3C;font-size:20px;"></i>
          <% else %>
            <a href="<%=contacts_path%>" class="btn btn-danger">Claim this Eatery?</a>
          <% end %>
            <% else %>
          <% if @restaurant.claimed? %>
            <i class="fa fa-check-circle" style="color:#EA4E3C;font-size:20px;"></i>
            <% else %>
            <i class="fa fa-times-circle" style="color:#EA4E3C;font-size:20px;"></i>
          <% end %>
        <% end %>
        <h4><%=@restaurant.category.title%></h4>
      </div>
    </div>
  </div>
  <!-- BREADCRUMBS -->
  <div class="container">
    <div class="row">
      <!-- RESTAURANT SLIDER -->
      <div class="col-md-7 property-slider">
        <figure>
          <img src="<%=@restaurant.primary_photo_url%>" alt="Image" class="img-responsive">
        </figure>
        <div class="thumbnails hidden-xs">
          <% @restaurant.restaurant_photos.not_primary.sample(3).each do |restaurant_photo| %>
            <img src="<%=restaurant_photo.photo.url%>" alt="Thumbnils" class="img-responsive">
          <% end %>
        </div>
      </div>
      <!-- RESTAURANT SLIDER -->
      <!-- RESTAURANT DATA -->
      <div class="col-md-5 property-data">
          <div class="prop-features prop-before">
            <iframe
              width="600"
              height="450"
              frameborder="0" style="border:0"
              src="<%=static_map_for(@restaurant)%>" allowfullscreen>
            </iframe>
            <span class="location"><%=@restaurant.address%></span>
            <% if lat_lng.present? %>
              <span class="area">DISTANCE: <%=number_to_human(@restaurant.distance_from(lat_lng, :km),
              units:
              :distance,
              precision: 4)%>
            </span>
            <% end %>
          </div>
          <div class="prop-price">
              <strong class="price">‎<%=@restaurant.price_range%></strong>
              <br><br>
              <div class="pull-left">
                <% if (user_signed_in? && (current_user.id == @restaurant.user_id)) %>
                  <%=  hidden_field :user_id , :value => current_user.id %>
                  <%= link_to "Edit your Eatery?", edit_restaurant_path(@restaurant), class: "btn btn-lg btn-danger" %>
                <% end %>
              </div>
              <br><br><br>
              <% if user_signed_in? %>
                <% if current_user.id != @restaurant.user_id %>
                  <%= render 'reviews/review' %>
                <% end %>
              <% else %>
                <%= link_to "Add Review", new_user_session_path, :class => "btn btn-danger" %>
              <% end %>
          </div>
      </div>
      <!-- RESTAURANT DATA -->
    </div>
  </div>
  <!-- COMMENT -->
  <%= render "reviews" %>
  <!-- COMMENT -->
</div>