config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'team-single' => 'contacts#team-single', as: 'team-single'
  root to: "home#index"

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :restaurants do
    resources :restaurant_photos
  end
  resources :contacts
  resources :reviews

end

app/models/restaurant_photo.rb
class RestaurantPhoto < ApplicationRecord
  belongs_to :restaurant

  has_attached_file :photo, styles: { thumb: "100x100>", big: "500x500>" }, default_url: "//s3.amazonaws.com/pickeat/eateries/default_photos/default-thumbnail.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  scope :not_primary, -> { where(primary: false) }
end

app/controllers/restaurant_photos_controller.rb
class RestaurantPhotosController < ApplicationController
  before_action :find_restaurant
  before_action :find_restaurant_photo, only: %w(edit destroy update)

  def index
    @restaurant_photos = @restaurant.restaurant_photos.order('created_at DESC')
  end

  def new
    @restaurant_photo = RestaurantPhoto.new
  end

  def create
    @restaurant_photo = RestaurantPhoto.new(permitted_params)
    @restaurant_photo.restaurant = @restaurant
    if @restaurant_photo.save
      flash[:success] = "Photo successfully created"
      redirect_to restaurant_restaurant_photos_path(@restaurant)
    else
      flash.now[:error] = @restaurant_photo.errors.full_messages.join(', ')
      render action: :new
    end
  end

  def edit 
  end

  def update
    @restaurant_photo.update_attributes(permitted_params)
    if @restaurant_photo.valid?
      flash.now[:success] = "Photo successfully updated"
      render action: :edit
    else
      flash.now[:error] = @restaurant_photo.errors.full_messages.join(', ')
      render action: :edit
    end
  end

  def destroy
    @restaurant_photo.destroy
    redirect_to restaurant_restaurant_photos_path(@restaurant)
  end

  private

  def find_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end

  def find_restaurant_photo
    @restaurant_photo = RestaurantPhoto.find(params[:id])
  end

  def permitted_params
    params.require(:restaurant_photo).permit(
      :id,
      :photo, 
      :primary
    )
  end
end

app/views/restaurant_photos/_form.html.erb
<div class="form-group">
  <% if f.object.photo.exists? %>
    <br/>
    <%=image_tag f.object.photo.url(:thumb), width: 100, class: 'img-responsive' %>
    <br/>
  <% end %>
  <%=f.label :photo %>
  <%=f.file_field :photo, accept:'image/*', class: 'form-control' %>
</div>
<div class="form-group">
  <%=f.label :primary %>
  <%=f.check_box :primary %>
</div>
<div class="form-group">
  <%=f.submit 'Submit', class: 'btn btn-danger' %>
  <%=link_to 'Cancel', restaurant_restaurant_photos_path(@restaurant), class: 'btn btn-default' %>
</div>

app/views/restaurant_photos/edit.html.erb
<div class="container">
  <ol class="breadcrumb">
   <li class="breadcrumb-item"> My Eatery </li>
   <li class="breadcrumb-item"> <%= @restaurant.name %></li>
   <li class="breadcrumb-item active"> <%=link_to 'Photos', restaurant_restaurant_photos_path(@restaurant) %></li>
  </ol>
  <div class="row col-md-6 col-md-offset-3">
    <h6 class="text-center"> Edit Photo </h6>
    <%=form_for [@restaurant, @restaurant_photo] do |f| %>
      <%= render partial: 'form', locals: {f: f} %>
    <% end %>
  </div>
</div>

app/views/restaurant_photos/index.html.erb
<div class="container">
  <ol class="breadcrumb">
   <li class="breadcrumb-item"> My Eatery </li>
   <li class="breadcrumb-item active"> <%=link_to @restaurant.name, edit_restaurant_path(@restaurant) %></li>
  </ol>
  <div class="row col-md-6 col-md-offset-3">
    <div class="pull-right">
      <%=link_to 'Add Photo', new_restaurant_restaurant_photo_path, class: 'btn btn-danger' %>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Photo</th>
          <th>Primary?</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @restaurant_photos.each do |photo| %>
          <tr>
            <td><%=image_tag photo.photo.url, width: 100, class: 'img-responsive' %></td>
            <td><%=photo.primary?%></td>
            <td>
              <%=link_to 'Delete', restaurant_restaurant_photo_path(@restaurant, photo), class: 'btn btn-warning', data: { confirm: "Are you sure you want to delete this photo?" }, method: :delete %>
              &nbsp;
              <%=link_to 'Edit', edit_restaurant_restaurant_photo_path(@restaurant, photo), class: 'btn btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/restaurant_photos/new.html.erb
<div class="container">
  <ol class="breadcrumb">
   <li class="breadcrumb-item"> My Eatery </li>
   <li class="breadcrumb-item"> <%= @restaurant.name %></li>
   <li class="breadcrumb-item active"> <%=link_to 'Photos', restaurant_restaurant_photos_path(@restaurant) %></li>
  </ol>
  <div class="row col-md-6 col-md-offset-3">
    <%=form_for @restaurant_photo, url: restaurant_restaurant_photos_path do |f| %>
      <%= render partial: 'form', locals: {f: f} %>
    <% end %>
  </div>
</div>